name: Add codesandbox link
on:
  pull_request:
    types: [opened]

jobs:
  codesandbox-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add comment
        uses: mshick/add-pr-comment@v2
        if: github.event.pull_request.head.repo.full_name == github.repository
        with:
          message: |
            Sandbox: https://githubbox.com/${{ github.repository }}/tree/${{ github.event.pull_request.head.ref }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
